version: '3.8'

volumes:
  mongodb_data:
    external: true

services:

  nodejs:
    image: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mern_nodejs
    command: /bin/sh -c "while sleep 1000; do :; done"  
    user: "node"
    # depends_on:
    #     - mongodb
    network_mode: service:mongodb
    volumes:
      - $HOME/DEV/MERN-projects:/workspace:cached

  mongodb:
    image: mongo
    container_name: mern_mongodb
    # restart: unless-stopped
    #init: true
    #network_mode: bridge
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123456
    #   MONGO_INITDB_DATABASE: example
    #   MONGO_INITDB_USERNAME: admin
    #   MONGO_INITDB_PASSWORD: 123456
    ports:
      - 27017:27017

