# FROM node:18-alpine
FROM node:20-alpine
RUN apk update && apk add --no-cache git
RUN npm install -g firebase-tools
# RUN addgroup -g 1000 developer && \
#     adduser -G developer -u 1000 developer -D
# USER developer
